import { University } from "@/types";

export const UNIVERSITIES: University[] = [
  {
    id: "1",
    name: "Lomonosov Moscow State University",
    nameRu: "МГУ им. М.В. Ломоносова",
    city: "Moscow",
    region: "Moscow (City)",
    lat: 55.7029,
    lng: 37.5303,
    programs: ["Physics", "History", "Math", "Biology"],
    fields: ["Science", "Humanities"],
    languages: ["Both"],
    levels: ["Bachelor", "Master", "PhD"],
    tuitionUSD: { min: 4500, max: 7000 },
    studentCount: 38000,
    internationalStudents: 4000,
    website: "https://www.msu.ru/en/",
    ranking: 1
  },
  {
    id: "2",
    name: "Saint Petersburg State University",
    nameRu: "СПбГУ",
    city: "Saint Petersburg",
    region: "Saint Petersburg (City)",
    lat: 59.9419,
    lng: 30.2985,
    programs: ["Management", "Social Sciences", "Art"],
    fields: ["Medicine", "Engineering"],
    languages: ["Both"],
    levels: ["Master", "PhD"],
    tuitionUSD: { min: 3500, max: 6000 },
    studentCount: 30000,
    internationalStudents: 3500,
    website: "https://english.spbu.ru/",
    ranking: 2
  },
  {
    id: "3",
    name: "RUDN University",
    nameRu: "РУДН",
    city: "Moscow",
    region: "Moscow (City)",
    lat: 55.6508,
    lng: 37.5056,
    programs: ["Medicine", "General Practice", "Law"],
    fields: ["Medicine", "Social Sciences"],
    languages: ["English"],
    levels: ["Bachelor", "Master"],
    tuitionUSD: { min: 5000, max: 9500 },
    studentCount: 32000,
    internationalStudents: 9500,
    website: "http://www.rudn.ru/en/",
    ranking: 10
  },
  {
    id: "4",
    name: "Kazan Federal University",
    nameRu: "КФУ",
    city: "Kazan",
    region: "Tatarstan Republic",
    lat: 55.7908,
    lng: 49.1219,
    programs: ["Oil & Gas", "Philology", "Chemistry"],
    fields: ["Engineering", "Science"],
    languages: ["Russian", "English"],
    levels: ["Bachelor", "Master"],
    tuitionUSD: { min: 2500, max: 4500 },
    studentCount: 45000,
    internationalStudents: 10000,
    website: "https://kpfu.ru/eng",
    ranking: 5
  },
  {
    id: "5",
    name: "Novosibirsk State University",
    nameRu: "НГУ",
    city: "Novosibirsk",
    region: "Novosibirsk Oblast",
    lat: 54.8432,
    lng: 83.0932,
    programs: ["Mathematics", "Nuclear Physics", "Biology"],
    fields: ["Science", "IT"],
    languages: ["Both"],
    levels: ["Bachelor", "Master", "PhD"],
    tuitionUSD: { min: 3000, max: 5500 },
    studentCount: 8000,
    internationalStudents: 1500,
    website: "https://english.nsu.ru/",
    ranking: 3
  },
  {
    id: "6",
    name: "Tomsk Polytechnic University",
    nameRu: "ТПУ",
    city: "Tomsk",
    region: "Tomsk Oblast",
    lat: 56.4697,
    lng: 84.9472,
    programs: ["Nuclear Engineering", "Cybernetics", "Petroleum"],
    fields: ["Engineering"],
    languages: ["Both"],
    levels: ["Bachelor", "Master"],
    tuitionUSD: { min: 2800, max: 4000 },
    studentCount: 15000,
    internationalStudents: 3000,
    website: "https://tpu.ru/en",
    ranking: 7
  },
  {
    id: "7",
    name: "Ural Federal University",
    nameRu: "УрФУ",
    city: "Ekaterinburg",
    region: "Sverdlovsk Oblast",
    lat: 56.8439,
    lng: 60.6536,
    programs: ["Mechanical Engineering", "Economics", "Philosophy"],
    fields: ["Engineering", "Business"],
    languages: ["Both"],
    levels: ["Bachelor", "Master", "PhD"],
    tuitionUSD: { min: 2200, max: 3800 },
    studentCount: 35000,
    internationalStudents: 4500,
    website: "https://urfu.ru/en/",
    ranking: 8
  },
  {
    id: "8",
    name: "Peter the Great St.Petersburg Polytechnic University",
    nameRu: "СПбПУ",
    city: "Saint Petersburg",
    region: "Saint Petersburg (City)",
    lat: 60.0071,
    lng: 30.3725,
    programs: ["Civil Engineering", "Physics", "Computer Science"],
    fields: ["Engineering", "IT"],
    languages: ["Both"],
    levels: ["Bachelor", "Master"],
    tuitionUSD: { min: 3000, max: 5000 },
    studentCount: 33000,
    internationalStudents: 8500,
    website: "https://english.spbstu.ru/",
    ranking: 9
  },
  {
    id: "9",
    name: "Southern Federal University",
    nameRu: "ЮФУ",
    city: "Rostov-on-Don",
    region: "Rostov Oblast",
    lat: 47.2271,
    lng: 39.7167,
    programs: ["Robotics", "Psychology", "International Relations"],
    fields: ["Engineering", "Humanities"],
    languages: ["Russian", "English"],
    levels: ["Bachelor", "Master"],
    tuitionUSD: { min: 1800, max: 3200 },
    studentCount: 25000,
    internationalStudents: 2500,
    website: "https://www.sfedu.ru/en",
    ranking: 15
  },
  {
    id: "10",
    name: "Far Eastern Federal University",
    nameRu: "ДВФУ",
    city: "Vladivostok",
    region: "Primorsky Krai",
    lat: 43.1194,
    lng: 131.8869,
    programs: ["Oceanography", "Bio-medicine", "Oriental Studies"],
    fields: ["Science", "Medicine"],
    languages: ["Both"],
    levels: ["Bachelor", "Master"],
    tuitionUSD: { min: 2500, max: 4800 },
    studentCount: 20000,
    internationalStudents: 3500,
    website: "https://www.dvfu.ru/en/",
    ranking: 12
  },
  {
    id: "11",
    name: "Belgorod State National Research University",
    nameRu: "БелГУ",
    city: "Belgorod",
    region: "Belgorod Oblast",
    lat: 50.5917,
    lng: 36.5786,
    programs: ["General Medicine", "Pharmacy", "Law"],
    fields: ["Medicine", "Social Sciences"],
    languages: ["Both"],
    levels: ["Bachelor", "Master"],
    tuitionUSD: { min: 3200, max: 5200 },
    studentCount: 23000,
    internationalStudents: 3200,
    website: "https://www.bsu.edu.ru/en/",
    ranking: 20
  },
  {
    id: "12",
    name: "Sechenov University",
    nameRu: "МГМУ им. Сеченова",
    city: "Moscow",
    region: "Moscow (City)",
    lat: 55.7275,
    lng: 37.5815,
    programs: ["Clinical Medicine", "Dentistry", "Pediatrics"],
    fields: ["Medicine"],
    languages: ["English", "Russian"],
    levels: ["Bachelor", "Master", "PhD"],
    tuitionUSD: { min: 6000, max: 11000 },
    studentCount: 19000,
    internationalStudents: 4500,
    website: "https://www.sechenov.ru/eng/",
    ranking: 4
  },
  {
    id: "13",
    name: "Samara National Research University",
    nameRu: "Самарский университет",
    city: "Samara",
    region: "Samara Oblast",
    lat: 53.2125,
    lng: 50.1772,
    programs: ["Aerospace Engineering", "Cosmonautics", "Engines"],
    fields: ["Engineering"],
    languages: ["Russian", "English"],
    levels: ["Bachelor", "Master"],
    tuitionUSD: { min: 2100, max: 3500 },
    studentCount: 16000,
    internationalStudents: 1200,
    website: "https://ssau.ru/english",
    ranking: 25
  },
  {
    id: "14",
    name: "Volgograd State Medical University",
    nameRu: "ВолгГМУ",
    city: "Volgograd",
    region: "Volgograd Oblast",
    lat: 48.7071,
    lng: 44.5161,
    programs: ["General Medicine", "Dentistry", "Medical Biochemistry"],
    fields: ["Medicine"],
    languages: ["English"],
    levels: ["Bachelor", "Master"],
    tuitionUSD: { min: 3800, max: 5000 },
    studentCount: 12000,
    internationalStudents: 2000,
    website: "https://www.volgmed.ru/en/",
    ranking: 30
  },
  {
    id: "15",
    name: "Saratov State University",
    nameRu: "СГУ",
    city: "Saratov",
    region: "Saratov Oblast",
    lat: 51.5332,
    lng: 46.0091,
    programs: ["Nanotechnology", "Geology", "Linguistics"],
    fields: ["Science", "Humanities"],
    languages: ["Russian"],
    levels: ["Bachelor", "Master"],
    tuitionUSD: { min: 1500, max: 2800 },
    studentCount: 18000,
    internationalStudents: 800,
    website: "https://www.sgu.ru/en",
    ranking: 35
  }
];
